add login/signup/oauth
HvAProjects/SuperSimpleSupplySystem pull request #15
Opened 2021-02-19 07:49 UTC by evaanp

2021-02-19 09:53 UTC, Davidsoff requested changes

2021-02-19 09:53 UTC, Davidsoff commented on backend/src/main/java/nl/jed/supersimplesupplysystem/dto/LocalUser.java
> +     *
lege javadoc

2021-02-19 09:53 UTC, Davidsoff commented on backend/src/main/java/nl/jed/supersimplesupplysystem/dto/LocalUser.java
> +    private nl.jed.supersimplesupplysystem.models.User user;
```suggestion
    @Getter
    private final OidcIdToken idToken;
    @Getter
    private final OidcUserInfo userInfo;
    @Getter @Setter
    private Map<String, Object> attributes;
    @Getter
    private nl.jed.supersimplesupplysystem.models.User user;
```

2021-02-19 09:53 UTC, Davidsoff commented on backend/src/main/java/nl/jed/supersimplesupplysystem/dto/LocalUser.java
> +    }
```suggestion
    @Override
    public String getName() {
        return this.user.getDisplayName();
    }
    
    @Override
    public Map<String, Object> getClaims() {
        return this.getAttributes();
    }
```

2021-02-19 09:53 UTC, Davidsoff commented on backend/src/main/java/nl/jed/supersimplesupplysystem/dto/LoginRequest.java
> +    }
```suggestion
    @NotBlank
    @Getter @Setter
    private String email;

    @NotBlank
    @Getter @Setter
    private String password;
```

2021-02-19 09:53 UTC, Davidsoff commented on backend/src/main/java/nl/jed/supersimplesupplysystem/dto/SignUpRequest.java
> +
getters and setters naar lombok omzetten

2021-02-19 09:53 UTC, Davidsoff commented on backend/src/main/java/nl/jed/supersimplesupplysystem/dto/SocialProvider.java
> +    }
```suggestion
    @Getter
    private String providerType;
```

2021-02-19 09:53 UTC, Davidsoff commented on backend/src/main/java/nl/jed/supersimplesupplysystem/models/User.java
> +public class User implements Serializable {
add lombok getters and setters

2021-02-19 09:53 UTC, Davidsoff commented on backend/src/main/java/nl/jed/supersimplesupplysystem/security/oauth2/user/OAuth2UserInfoFactory.java
> +public class OAuth2UserInfoFactory {
heel veel if else statements, even kijken of we dat om kunnen schrijven naar iets war fijner is om mee te werken

2021-02-19 09:53 UTC, Davidsoff commented on backend/src/main/resources/application.properties
> +server.port=8080
8080 is al in gebruik op mijn machine, kunnen we 8081 of een andere poort gebruiken?

2021-02-19 09:53 UTC, Davidsoff commented
we missen ook de tests in de backend

2021-02-19 11:56 UTC, evaanp commented on backend/src/main/java/nl/jed/supersimplesupplysystem/configuration/VersionLogger.java
> +//import nl.jed.BuildConfig;
Foutje, bij mij werkt het niet, hij zegt dat de BuildConfig niet gevonden kan worden

2021-03-04 19:35 UTC, Davidsoff approved these changes

2021-03-04 19:35 UTC, merged